### ISSUE TITLE
Integrating PyBossa with Mapknitter

### ISSUE THREAD

**Issue by teleyinex** [jywarren/mapknitter#143]
Hi,

I've been integrating MapKnitter with Pybossa (you can see a demo [here](http://crowdcrafting.org/app/mapknitter/)), and I wonder if you could export more info on the page of the maps regarding for example the bounding box. That would allow other people to actually use that information in third party solutions like PyBossa.

Maybe, the simple thing to do could be to generate a JSON URL for each map:

http://mapknitter.org/user/map/tms.json

That would have the information regarding the server URL, Bounding Box of the created map by the user, etc.

What do you think?

**Comment by jywarren** [comment]
Moving to https://github.com/publiclab/mapknitter/issues/75 thanks!!
