### ISSUE TITLE
edit permissions in mapknitter

### ISSUE THREAD

**Issue by fiestin** [jywarren/mapknitter#149]
solving the problem of random edits to a map that damage the data created. thinking about creating a system for editable/non-editable in maps, but also, for longer term planning, desgining the ability to send a link to the map that embeds edit/view options for users.

**Comment by jywarren** [comment]
Some of this has been addressed, but if you could make an issue for "locked" maps on https://github.com/publiclab/mapknitter/issues that would be great, thanks!
