### ISSUE TITLE
error in attempting to upload JPEG cropped in Graphic Convertor

### ISSUE THREAD

**Issue by patcoyle** [jywarren/mapknitter#150]
Yesterday and this morning I had knitter save my maps as anonymous rather than my username. Also, complained initially about address not being specific enough. See the EWB regional workshop San Diego ca and ditto vis in progress maps.
Also, got error in attempting to upload JPEG cropped in Graphic Convertor.

**Comment by jywarren** [comment]
Hi Pat, can you check if this happens on mapknitter.org now? We use a different image processor. Not the Mapknitter 2 beta, just the current production server. If it does, could you copy the error you see and relevant info to https://github.com/publiclab/mapknitter/issues please? Thanks.

**Comment by patcoyle** [comment]
Thanks Jeff,

I checked a different map in current mapknitter with a Graphic Convertor
cropped image in Firefox and the upload worked fine. See:
http://mapknitter.org/maps/livermore-ca-test-with-pl-mobius-infragram-point-and-shoot-on-parrot-ar-drone-2-0

and attached screenshot.
