### ISSUE TITLE
Embed code issues

### ISSUE THREAD

**Issue by patcoyle** [jywarren/mapknitter#183]
In Firefox map http://mapknitter.org/maps/dji-gimp-lens-corrected-image, Embed code button doesn't produce code to embed map in PL note. Ditto for Safari and Chrome. Is there a different way to get html to embed as was available in past?

**Comment by jywarren** [comment]
Oh, Pat, could you re-file this at https://github.com/publiclab/mapknitter/issues/new -- this tracker is no longer in use! Thanks so much for reporting!

**Comment by patcoyle** [comment]
Done. Thanks Jeff.
