### ISSUE TITLE
Can't start new map.

### ISSUE THREAD

**Issue by joshclough** [jywarren/mapknitter#184]
After selecting " create a map anonymously." the button to do so pops up, but then when pushed goes to the address "http://localhost:3000/maps/new" but displays the folowing error:

NoMethodError in Maps#new

Showing /home/john/mapknitter/app/views/maps/new.html.erb where line #74 raised:

undefined method `recaptcha_tags' for #<#<Class:0x00000001f2c320>:0x007f4abd00b748>

Extracted source (around line #74):

71:       </select>
72:     </div>
73: 
74:     <% if !logged_in? %><p><%= recaptcha_tags :display => {:theme => "white"} %></p><% end %>
75: 
76:     <%= f.submit "Create map", :class => "btn btn-primary btn-lg", :tabIndex => 4 %>  
77:

**Comment by jywarren** [comment]
Ah, do you have recaptcha installed (via Bower, explained in Readme) and
API keys set up?

Also, the latest code is now kept at https://github.com/publiclab/mapknitter
and issues at https://github.com/publiclab/mapknitter/issues

Can you copy this over there?

After selecting " create a map anonymously." the button to do so pops up,
but then when pushed goes to the address "http://localhost:3000/maps/new"
but displays the folowing error:

NoMethodError in Maps#new

Showing /home/john/mapknitter/app/views/maps/new.html.erb where line #74
<https://github.com/jywarren/mapknitter/issues/74> raised:

undefined method `recaptcha_tags' for
#<#Class:0x00000001f2c320:0x007f4abd00b748>

Extracted source (around line #74
<https://github.com/jywarren/mapknitter/issues/74>):

71:
72:
73:
74: <% if !logged_in? %>

<%= recaptcha_tags :display => {:theme => "white"} %>
<% end %>
75:
76: <%= f.submit "Create map", :class => "btn btn-primary btn-lg",
:tabIndex => 4 %>

77:

—
Reply to this email directly or view it on GitHub
<https://github.com/jywarren/mapknitter/issues/184>.

**Comment by joshclough** [comment]
(the short version of this is I think I just need to know what the keys are)
I renamed the recaptcha example file to just recaptcha.rb.
Which now makes the map making page load, but when I click create map
I get stuff like "here was a problem creating the map

    ReCAPTCHA thinks you're not human! Try again!
    translation missing: en.wrong_captcha"
and
"Input error: k: Format of site key was invalid "

The key file doesn't seem to have the keys in it (all XXXXX)
but going to the website in the read me at: https://google.com/recaptcha/admin
goes nowheres.

**Comment by jywarren** [comment]
Oh! The URL is apparently now
http://www.google.com/recaptcha/intro/index.html

Would you be able to post an edit to the readme?
